version: 2.1

orbs:
  python: circleci/python@1.0.0
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # pip-dependency-file: requirements.txt
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linter
          command: flake8

  # publish-dockerhub:
  #   docker:
  #     - image: cimg/python:3.11.1
  #   steps:
  #     - checkout
  #     - setup_remote_docker
  #     - run:
  #         name: Publish to Docker Hub
  #         command: |
  #           IMAGE_NAME=$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$CIRCLE_BRANCH-$CIRCLE_SHA1

            # docker build -t $IMAGE_NAME .
            # echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USERNAME --password-stdin
            # docker push $IMAGE_NAME

  pub-dock:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKERHUB_USERNAME/$DOCKERHUB_REPO
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $DOCKERHUB_USERNAME/$DOCKERHUB_REPO
          tag: $CIRCLE_SHA1


  heroku-deployment:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      # - run:
      #     name: Deploying the docker image
      #     command: >
      #       echo "The command above installs Heroku, the command below deploys.
      #       What you do inbetween is up to you!"
      - heroku/deploy-via-git

workflows:
  lettings-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main

      # - publish-dockerhub:
      - pub-dock:
          context:
            - oc-lettings-context
          requires:
            - build-and-test


      - heroku-deployment:
          context:
            - oc-lettings-context
          requires:
            - pub-dock
            # - publish-dockerhub
