version: 2.1

orbs:
  python: circleci/python@1.0.0
  docker: circleci/docker@2.2.0
  heroku: circleci/heroku@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # pip-dependency-file: requirements.txt
      - run:
          name: Tests
          command: pytest
      - run:
          name: Linter
          command: flake8

  publish-dockerhub:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_LOGIN/$HEROKU_APP_NAME
          tag: $CIRCLE_BRANCH-$CIRCLE_SHA1
      - docker/push:
          image: $DOCKER_LOGIN/$HEROKU_APP_NAME
          tag: $CIRCLE_BRANCH-$CIRCLE_SHA1

  heroku-deployment:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  lettings-workflow:
    jobs:
      - build-and-test

      - publish-dockerhub:
          context:
            - oc-lettings-context
          requires:
            - build-and-test
          filters:
            branches:
              only: main

      - heroku-deployment:
          context:
            - oc-lettings-context
          requires:
            - publish-dockerhub
